### ISSUE TITLE
dead ? ERROR:  Could not find a valid gem 'dronr' (>= 0) in any repository

### ISSUE THREAD

**Issue by alexey** [recombinary/dronr#1]
$ gem install dronr
`ERROR:  Could not find a valid gem 'dronr' (>= 0) in any repository`

**Comment by jeriko** [comment]
Looking into it..

**Comment by jeriko** [comment]
@alexey fixed. Will work on adding more drones over the next few months.

**Comment by alexey** [comment]
thanks @jeriko !
